# Homebrew cask for Synapify - the visual RIDDL editor
# To install: brew install --cask ossuminc/tap/synapify
# Or add the tap first: brew tap ossuminc/tap && brew install --cask synapify
# Auto-generated by update-synapify.yml - do not edit manually

cask "synapify" do
  version "0.17.0"
  sha256 "234fa66af3cd939e1875ac69ffe11f170273e0c515aba49cf9e6c335e34e5c03"

  # ossuminc/synapify is a private repo, so its GitHub release assets
  # 404 for anonymous downloads. The GCS bucket is the public
  # distribution channel — the same one the website and riddlg use.
  url "https://storage.googleapis.com/synapify-releases/#{version}/Synapify-#{version}-arm64.dmg"
  name "Synapify"
  desc "Visual RIDDL editor for designing distributed, reactive systems"
  homepage "https://ossum.ai/products/synapify"

  livecheck do
    url "https://storage.googleapis.com/synapify-releases/latest.json"
    strategy :json do |json|
      json["version"]
    end
  end

  # Synapify updates itself via electron-updater against the GCS
  # release bucket, so `brew upgrade` leaves it alone unless asked
  # with --greedy; this cask version governs fresh installs only.
  # Only an arm64 build exists, because synapify's release workflow
  # runs its macOS job on a macos-14 runner and electron-builder
  # targets the host architecture. A bare `macos:` symbol means that
  # version or newer (MacOSRequirement defaults to a >= comparator).
  auto_updates true
  depends_on macos: :monterey
  depends_on arch: :arm64

  app "Synapify.app"

  zap trash: [
    "~/Library/Application Support/Synapify",
    "~/Library/Caches/com.ossuminc.synapify",
    "~/Library/Logs/Synapify",
    "~/Library/Preferences/com.ossuminc.synapify.plist",
    "~/Library/Saved Application State/com.ossuminc.synapify.savedState",
  ]
end
