# Homebrew formula for riddlc - the RIDDL compiler
# To install: brew install ossuminc/tap/riddlc
# Or add the tap first: brew tap ossuminc/tap && brew install riddlc
# Auto-generated by update-formula.yml - do not edit manually

class Riddlc < Formula
  desc "Compiler for RIDDL (Reactive Interface to Domain Definition Language)"
  homepage "https://github.com/ossuminc/riddl"
  version "1.15.5"
  license "Apache-2.0"

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/ossuminc/riddl/releases/download/#{version}/riddlc-macos-arm64.zip"
    sha256 "354aceac7498e7115df42fec7f87df0a3e507c1d84ab4705ccc04f0299d51562"
  elsif OS.linux? && Hardware::CPU.intel?
    url "https://github.com/ossuminc/riddl/releases/download/#{version}/riddlc-linux-x86_64.zip"
    sha256 "15fff190e37750cdbc0784e09954a319af254ba688cc5206938c51e4be7ef0ee"
  else
    url "https://github.com/ossuminc/riddl/releases/download/#{version}/riddlc.zip"
    sha256 "ffeb92c958113dbeb9e436e837dd29b865e9e41cbb6ed08796bb3b40f7a6f2df"
    depends_on "openjdk@21"
  end

  def install
    if (OS.mac? && Hardware::CPU.arm?) || (OS.linux? && Hardware::CPU.intel?)
      # Native binary - Homebrew strips the single top-level "bin/" dir
      bin.install "riddlc"
    else
      # JVM version - needs wrapper script
      rm "bin/riddlc.bat"
      libexec.install "lib"
      libexec.install "bin"

      (bin/"riddlc").write <<~EOS
        #!/bin/bash
        export JAVA_HOME="#{Formula["openjdk@21"].opt_prefix}"
        exec "#{libexec}/bin/riddlc" "$@"
      EOS
    end
  end

  def caveats
    if (OS.mac? && Hardware::CPU.arm?) || (OS.linux? && Hardware::CPU.intel?)
      <<~EOS
        riddlc is installed as a native binary. No JDK required.

        To verify the installation:
          riddlc version

        For help:
          riddlc help
      EOS
    else
      <<~EOS
        riddlc requires Java 21. This formula uses openjdk@21.

        To verify the installation:
          riddlc version

        For help:
          riddlc help
      EOS
    end
  end

  test do
    assert_match "riddlc version", shell_output("#{bin}/riddlc version")
  end
end
