# Homebrew formula for riddlg — local RIDDL generation, simulation & codegen
# (the riddl-generator native binary).
# To install: brew install ossuminc/tap/riddlg
# Or: brew tap ossuminc/tap && brew install riddlg
# Auto-generated by update-riddlg.yml - do not edit manually

class Riddlg < Formula
  desc "Local RIDDL validation, docs/API generation, and AI code generation"
  homepage "https://ossum.tech/riddl/tools/riddlg/"
  version "0.4.0"
  license :cannot_represent # proprietary; not open source

  # Native binary + a vendored libllama (in lib/, found via @rpath/$ORIGIN).
  if OS.mac? && Hardware::CPU.arm?
    url "https://storage.googleapis.com/synapify-releases/riddlg/#{version}/riddlg-#{version}-Darwin-arm64.tar.gz"
    sha256 "498d475d5318db2e67be09952ede828cf6b3cc5f22437d7bbea50ba15a4d4564"
    depends_on "libidn2"
    depends_on "openssl@3"
  elsif OS.linux? && Hardware::CPU.intel?
    url "https://storage.googleapis.com/synapify-releases/riddlg/#{version}/riddlg-#{version}-Linux-x86_64.tar.gz"
    sha256 "24f45bb54619f19cb4a5448d8d6458cc1688f3649fbbc8736d9ecbdea03ba7d8"
    depends_on "libidn2"
    depends_on "openssl@3"
  else
    odie "riddlg has prebuilt binaries only for macOS arm64 and Linux x86_64"
  end

  def install
    # Vendored libllama/ggml are private to riddlg (found via the binary's
    # @executable_path/../lib rpath, and $ORIGIN/../lib on Linux). Install them
    # under libexec so Homebrew does NOT symlink them into HOMEBREW_PREFIX/lib
    # and collide with the ggml / llama.cpp formulae; only the binary goes on
    # the PATH. bin and lib stay siblings in libexec, so the rpath still works.
    libexec.install "bin", "lib"
    bin.install_symlink libexec/"bin/riddlg"
  end

  def caveats
    <<~EOS
      riddlg is a native binary; libllama is vendored (no separate install).

      The default AI model is downloaded on first use of `gen riddl`
      (~/.ossum-ai/models). Override with --model or OSSUM_GEN_MODEL_URL.

      Pro features (Quarkus code generation) require a license:
      set OSSUM_GEN_LICENSE or place a token at ~/.ossum-gen/license.

      Verify:  riddlg info
    EOS
  end

  test do
    assert_match "riddlg", shell_output("#{bin}/riddlg --help 2>&1")
  end
end
