# Homebrew formula for riddl-gen-cli - document generators for RIDDL models
# To install: brew install ossuminc/tap/riddl-gen-cli
# Or add the tap first: brew tap ossuminc/tap && brew install riddl-gen-cli
# Auto-generated by update-riddl-gen-formula.yml - do not edit manually

class RiddlGenCli < Formula
  desc "Document generators for RIDDL (Reactive Interface to Domain Definition Language) models"
  homepage "https://github.com/ossuminc/riddl-gen"
  version "0.3.5"
  license "Apache-2.0"

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/ossuminc/riddl-gen/releases/download/#{version}/riddl-gen-cli-macos-aarch64.tar.gz"
    sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  elsif OS.linux? && Hardware::CPU.intel?
    url "https://github.com/ossuminc/riddl-gen/releases/download/#{version}/riddl-gen-cli-linux-amd64.tar.gz"
    sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  else
    url "https://github.com/ossuminc/riddl-gen/releases/download/#{version}/riddl-gen-cli-jvm.tgz"
    sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    depends_on "openjdk@25"
  end

  def install
    if (OS.mac? && Hardware::CPU.arm?) || (OS.linux? && Hardware::CPU.intel?)
      # Native binary from tar.gz
      bin.install "riddl-gen-cli"
    else
      # JVM version - needs wrapper script
      rm "bin/riddl-gen-cli.bat" if File.exist?("bin/riddl-gen-cli.bat")
      libexec.install "lib"
      libexec.install "bin"

      (bin/"riddl-gen-cli").write <<~EOS
        #!/bin/bash
        export JAVA_HOME="#{Formula["openjdk@25"].opt_prefix}"
        exec "#{libexec}/bin/riddl-gen-cli" "$@"
      EOS
    end
  end

  def caveats
    if (OS.mac? && Hardware::CPU.arm?) || (OS.linux? && Hardware::CPU.intel?)
      <<~EOS
        riddl-gen-cli is installed as a native binary. No JDK required.

        To verify the installation:
          riddl-gen-cli --help

        For usage:
          riddl-gen-cli generate --help
      EOS
    else
      <<~EOS
        riddl-gen-cli requires Java 25. This formula uses openjdk@25.

        To verify the installation:
          riddl-gen-cli --help

        For usage:
          riddl-gen-cli generate --help
      EOS
    end
  end

  test do
    assert_match "riddl-gen-cli", shell_output("#{bin}/riddl-gen-cli --help")
  end
end
