# Homebrew formula for riddlc - the RIDDL compiler
# To install: brew install ossuminc/tap/riddlc
# Or add the tap first: brew tap ossuminc/tap && brew install riddlc
# Auto-generated by update-formula.yml - do not edit manually

class Riddlc < Formula
  desc "Compiler for RIDDL (Reactive Interface to Domain Definition Language)"
  homepage "https://github.com/ossuminc/riddl"
  version "2.3.0"
  license "Apache-2.0"

  # riddlc and riddlc-rc are mutually exclusive rather than the RC being
  # keg_only: a release candidate exists to be exercised as `riddlc` on
  # PATH, which a keg_only formula would not be.
  conflicts_with "riddlc-rc", because: "both install a riddlc binary"

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/ossuminc/riddl/releases/download/#{version}/riddlc-macos-arm64.zip"
    sha256 "af5141a3a133d0c90ab7864d9c572e37e98cf840bf223e5ac0b003eaf6a8fdb8"
    depends_on "libidn2"
    depends_on "openssl@3"
  elsif OS.linux? && Hardware::CPU.intel?
    url "https://github.com/ossuminc/riddl/releases/download/#{version}/riddlc-linux-x86_64.zip"
    sha256 "a2a15fe247a2178c1a9e36a6ec1ddf8e40a2c279c4dc22a6a46f64a07a687e16"
    depends_on "libidn2"
    depends_on "openssl@3"
  else
    url "https://github.com/ossuminc/riddl/releases/download/#{version}/riddlc.zip"
    sha256 "42921300cc936f61ef2ab673a8a81494b059e5ae572ee75da408c81bc3bc077b"
    depends_on "openjdk@21"
  end

  def install
    if (OS.mac? && Hardware::CPU.arm?) || (OS.linux? && Hardware::CPU.intel?)
      # Native binary - Homebrew strips the single top-level "bin/" dir
      bin.install "riddlc"
    else
      # JVM version - needs wrapper script
      rm "bin/riddlc.bat"
      libexec.install "lib"
      libexec.install "bin"

      (bin/"riddlc").write <<~EOS
        #!/bin/bash
        export JAVA_HOME="#{Formula["openjdk@21"].opt_prefix}"
        exec "#{libexec}/bin/riddlc" "$@"
      EOS
    end
  end

  def caveats
    if (OS.mac? && Hardware::CPU.arm?) || (OS.linux? && Hardware::CPU.intel?)
      <<~EOS
        riddlc is installed as a native binary. No JDK required.

        To verify the installation and see what you got:
          riddlc info

        For help:
          riddlc help
      EOS
    else
      <<~EOS
        riddlc requires Java 21. This formula uses openjdk@21.

        To verify the installation and see what you got:
          riddlc info

        For help:
          riddlc help
      EOS
    end
  end

  test do
    # `riddlc info` proves the binary runs AND that it reports the
    # version this formula claims to have installed.
    assert_match version.to_s, shell_output("#{bin}/riddlc info")
  end
end
