# Homebrew formula for riddlg-rc — local RIDDL generation & codegen
# (the riddl-generator native binary).
# To install: brew install ossuminc/tap/riddlg-rc
# Or: brew tap ossuminc/tap && brew install riddlg-rc
# Auto-generated by update-riddlg.yml - do not edit manually

class RiddlgRc < Formula
  desc "Release candidate of riddlg, the RIDDL generator"
  homepage "https://ossum.tech/riddl/tools/riddlg/"
  version "1.0.0-rc.4"
  license :cannot_represent # proprietary; not open source

  # Not keg_only: a release candidate exists to be exercised as `riddlg`
  # on PATH, which a keg_only formula would not be. The two lines
  # therefore conflict, and say so in both directions.
  conflicts_with "riddlg", because: "both install a riddlg binary"

  # Native binary + a vendored libllama (in lib/, found via @rpath/$ORIGIN).
  if OS.mac? && Hardware::CPU.arm?
    url "https://storage.googleapis.com/synapify-releases/riddlg/#{version}/riddlg-#{version}-Darwin-arm64.tar.gz"
    sha256 "7d357d9cd3fcbb94e7e05525e12ba9b76f1b7b56566bc11296579adee2a0e3e8"
    depends_on "libidn2"
    depends_on "openssl@3"
  elsif OS.linux? && Hardware::CPU.intel?
    url "https://storage.googleapis.com/synapify-releases/riddlg/#{version}/riddlg-#{version}-Linux-x86_64.tar.gz"
    sha256 "3ba81e4ec29c9c43ca04c13ff047d074b1950f8252925fb77b7ba7a65ad9cf2b"
    depends_on "libidn2"
    depends_on "openssl@3"
  else
    odie "riddlg has prebuilt binaries only for macOS arm64 and Linux x86_64"
  end

  def install
    # Vendored libllama/ggml are private to riddlg (found via the binary's
    # @executable_path/../lib rpath, and $ORIGIN/../lib on Linux). Install them
    # under libexec so Homebrew does NOT symlink them into HOMEBREW_PREFIX/lib
    # and collide with the ggml / llama.cpp formulae; only the binary goes on
    # the PATH. bin and lib stay siblings in libexec, so the rpath still works.
    libexec.install "bin", "lib"
    bin.install_symlink libexec/"bin/riddlg"
  end

  def caveats
    <<~EOS
      riddlg is a native binary; libllama is vendored (no separate install).

      Everything riddlg owns lives under one directory: a .riddlg in the
      working directory if there is one, else ~/.riddlg. The default AI
      model is downloaded on first use of `gen riddl` into
      <riddlg-home>/models; override with --model or RIDDLG_MODEL_URL.

      Pro features (Quarkus code generation, cloud AI providers) come with
      an Ossum subscription: run `riddlg login`.

      Verify:  riddlg info
    EOS
  end

  test do
    assert_match "riddlg", shell_output("#{bin}/riddlg --help 2>&1")
  end
end
