# Homebrew formula for riddlc-rc - the RIDDL compiler
# To install: brew install ossuminc/tap/riddlc-rc
# Or add the tap first: brew tap ossuminc/tap && brew install riddlc-rc
# Auto-generated by update-formula.yml - do not edit manually

class RiddlcRc < Formula
  desc "Release candidate of riddlc, the RIDDL compiler"
  homepage "https://github.com/ossuminc/riddl"
  version "2.0.0-rc.11"
  license "Apache-2.0"

  # riddlc and riddlc-rc are mutually exclusive rather than the RC being
  # keg_only: a release candidate exists to be exercised as `riddlc` on
  # PATH, which a keg_only formula would not be.
  conflicts_with "riddlc", because: "both install a riddlc binary"

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/ossuminc/riddl/releases/download/#{version}/riddlc-macos-arm64.zip"
    sha256 "d1b49330f09e53dd73ab75c969bf1ec7e70273b77b89a85d276d7cfeb9d90fc0"
    depends_on "libidn2"
    depends_on "openssl@3"
  elsif OS.linux? && Hardware::CPU.intel?
    url "https://github.com/ossuminc/riddl/releases/download/#{version}/riddlc-linux-x86_64.zip"
    sha256 "15f097ff74d3f44ee949f7d2805931cd1975eb7b3494cb9c98cce2cf55e33dab"
    depends_on "libidn2"
    depends_on "openssl@3"
  else
    url "https://github.com/ossuminc/riddl/releases/download/#{version}/riddlc.zip"
    sha256 "0b8130b454cdb86132cab465ca9a2c6a183bdafc870c82c40e08ab0ca723a1fc"
    depends_on "openjdk@21"
  end

  def install
    if (OS.mac? && Hardware::CPU.arm?) || (OS.linux? && Hardware::CPU.intel?)
      # Native binary - Homebrew strips the single top-level "bin/" dir
      bin.install "riddlc"
    else
      # JVM version - needs wrapper script
      rm "bin/riddlc.bat"
      libexec.install "lib"
      libexec.install "bin"

      (bin/"riddlc").write <<~EOS
        #!/bin/bash
        export JAVA_HOME="#{Formula["openjdk@21"].opt_prefix}"
        exec "#{libexec}/bin/riddlc" "$@"
      EOS
    end
  end

  def caveats
    if (OS.mac? && Hardware::CPU.arm?) || (OS.linux? && Hardware::CPU.intel?)
      <<~EOS
        riddlc is installed as a native binary. No JDK required.

        To verify the installation and see what you got:
          riddlc info

        For help:
          riddlc help
      EOS
    else
      <<~EOS
        riddlc requires Java 21. This formula uses openjdk@21.

        To verify the installation and see what you got:
          riddlc info

        For help:
          riddlc help
      EOS
    end
  end

  test do
    # `riddlc info` proves the binary runs AND that it reports the
    # version this formula claims to have installed.
    assert_match version.to_s, shell_output("#{bin}/riddlc info")
  end
end
